### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by R2D2Hud** [XilefTech/CharlieOSX#15]
Not working

I see the play symbol then there is a beep and the program exits.

The contents of main.py.err.log

`
[[ChalieOSX]] [Debug] Started loading settings
[[ChalieOSX}] [Debug] Successfully loaded settings
[08.09.2020-21:15:00] [Logger] [Info] Initialisating Logger
[08.09.2020-21:15:00] [Logger] [Info] Logger initialized
[08.09.2020-21:15:00] [ConfigParser] [Info] Started config parsing
[08.09.2020-21:15:01] [ConfigParser] [Info] Finished config parsing
[08.09.2020-21:15:01] [Charlie] [Info] Starting initialisation of Charlie
[08.09.2020-21:15:01] [Charlie] [Debug] Starting sensor initialisation...
[08.09.2020-21:15:01] [Charlie] [Debug] Gyrosensor initialized sucessfully on port 0
[08.09.2020-21:15:01] [Charlie] [Debug] Colorsensor initialized sucessfully on port 0
[08.09.2020-21:15:01] [Charlie] [Debug] Colorsensor initialized sucessfully on port 0
[08.09.2020-21:15:01] [Charlie] [Debug] Touchsensor initialized sucessfully on port 0
[08.09.2020-21:15:01] [Charlie] [Debug] Sensor initialisation done
[08.09.2020-21:15:01] [Charlie] [Debug] Starting motor initialisation...
[08.09.2020-21:15:01] [Charlie] [Error] Failed to initialize movement motors for robot type NORMAL - Are u sure they're all connected?: TypeError: object 'str' isn't a tuple or list
Traceback (most recent call last):
  File "/home/robot/CharlieOSX-master/main.py", line 20, in <module>
  File "/home/robot/CharlieOSX-master/charlieosx.py", line 32, in __init__
  File "/home/robot/CharlieOSX-master/robot.py", line 27, in __init__
  File "/home/robot/CharlieOSX-master/robot.py", line 78, in __initMotors
  File "/home/robot/CharlieOSX-master/robot.py", line 78, in __initMotors
  File "/home/robot/CharlieOSX-master/logging.py", line 167, in error
TypeError: can't convert 'TypeError' object to str implicitly

`

**Comment by XilefTech** [comment]
This is a known thing for me, I planned on fixing tonight anyway. (dunno if I can finish it tonight tho)
The problem is, that my config parser currently parses the array that you enter for the gears as a string. but the function expects an array. If you immediately want to test/use charlieOSX, just go back a few commits to before the gearing support was added or wait a few hours until I (hopefully) have fixed the configparser ;)

But thanks for testing/using CharlieOSX anyway. I need ppl like u to find all the little and silly mistakes I made over the time since I havn't got so much time for actual testing ;)

**Comment by XilefTech** [comment]
Okay, so now I pushed a hotfix that should make it work again, along with fixing some other little things.
Gearings are still not working yet, since the proper parsing of the arrays will take a bit longer than I got time for this evening. But I'll finish it tomorrow.

**Comment by R2D2Hud** [comment]
Okay I will test it when i get time

**Comment by R2D2Hud** [comment]
now it just exit's

contents of main.py.err.log

/usr/bin/env: 'pybricks-micropython\r': No such file or directory

**Comment by dlech** [comment]
> /usr/bin/env: 'pybricks-micropython\r': No such file or directory

Be sure to save the file with Unix line endings. This error is caused by Windows line endings.

**Comment by XilefTech** [comment]
Yep, as @dlech said, this has to do with the line endings. somehow, even if I save it correctly, github seemingly doesn't want to.
![image](https://user-images.githubusercontent.com/52332196/92660975-d277c880-f2fb-11ea-9106-7e89979ce43a.png)
Make sure it's set to LF

just in case you didn't know it ;)

**Comment by XilefTech** [comment]
Also now added a little note about it in the [installation wiki](https://github.com/XilefTech/CharlieOSX/wiki/Installation)

**Comment by dlech** [comment]
You can also add a `.gitattributes` file with the line `*.py text eol=lf` to force git to always check out .py files with unix line endings.

**Comment by XilefTech** [comment]
oh thanks, I'll do that!

**Comment by R2D2Hud** [comment]
Okay now It work's. And love CharlieOSX
